[build]
  base = "web"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  FRONTEND_PORT = "9011"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "src/pages/api" 